package com.axd.mybatis.mapper;

import com.axd.mybatis.model.TbAdvertPosition;
import com.axd.mybatis.model.TbAdvertPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAdvertPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    long countByExample(TbAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    int insert(TbAdvertPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    int insertSelective(TbAdvertPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    List<TbAdvertPosition> selectByExample(TbAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdvertPosition record, @Param("example") TbAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdvertPosition record, @Param("example") TbAdvertPositionExample example);
}