package com.axd.mybatis.mapper;

import com.axd.mybatis.model.TbAdvertContent;
import com.axd.mybatis.model.TbAdvertContentExample;
import java.util.List;


import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbAdvertContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    long countByExample(TbAdvertContentExample example);
    List<TbAdvertContent> selectAll();
    public TbAdvertContent getById(@Param(value = "id") Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdvertContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int insert(TbAdvertContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int insertSelective(TbAdvertContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    List<TbAdvertContent> selectByExampleWithBLOBs(TbAdvertContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    List<TbAdvertContent> selectByExample(TbAdvertContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdvertContent record, @Param("example") TbAdvertContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbAdvertContent record, @Param("example") TbAdvertContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdvertContent record, @Param("example") TbAdvertContentExample example);
}