package com.axd.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_advert_position
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TbAdvertPosition implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   广告位描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.position_name
     *
     * @mbg.generated
     */
    private String positionName;

    /**
     * Database Column Remarks:
     *   广告位标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.position_desc
     *
     * @mbg.generated
     */
    private String positionDesc;

    /**
     * Database Column Remarks:
     *   图片尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.pic_size
     *
     * @mbg.generated
     */
    private String picSize;

    /**
     * Database Column Remarks:
     *   广告数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.count
     *
     * @mbg.generated
     */
    private Boolean count;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.utime
     *
     * @mbg.generated
     */
    private Integer utime;

    /**
     * Database Column Remarks:
     *   状态(1:启用 2:禁用)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_position.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_advert_position
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.id
     *
     * @return the value of tb_advert_position.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.id
     *
     * @param id the value for tb_advert_position.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.position_name
     *
     * @return the value of tb_advert_position.position_name
     *
     * @mbg.generated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.position_name
     *
     * @param positionName the value for tb_advert_position.position_name
     *
     * @mbg.generated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.position_desc
     *
     * @return the value of tb_advert_position.position_desc
     *
     * @mbg.generated
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.position_desc
     *
     * @param positionDesc the value for tb_advert_position.position_desc
     *
     * @mbg.generated
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.pic_size
     *
     * @return the value of tb_advert_position.pic_size
     *
     * @mbg.generated
     */
    public String getPicSize() {
        return picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.pic_size
     *
     * @param picSize the value for tb_advert_position.pic_size
     *
     * @mbg.generated
     */
    public void setPicSize(String picSize) {
        this.picSize = picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.count
     *
     * @return the value of tb_advert_position.count
     *
     * @mbg.generated
     */
    public Boolean getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.count
     *
     * @param count the value for tb_advert_position.count
     *
     * @mbg.generated
     */
    public void setCount(Boolean count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.ctime
     *
     * @return the value of tb_advert_position.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.ctime
     *
     * @param ctime the value for tb_advert_position.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.utime
     *
     * @return the value of tb_advert_position.utime
     *
     * @mbg.generated
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.utime
     *
     * @param utime the value for tb_advert_position.utime
     *
     * @mbg.generated
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.status
     *
     * @return the value of tb_advert_position.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.status
     *
     * @param status the value for tb_advert_position.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_position.admin_id
     *
     * @return the value of tb_advert_position.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_position.admin_id
     *
     * @param adminId the value for tb_advert_position.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}