package com.axd.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_advert_content
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TbAdvertContent implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属广告Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.position_id
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     * Database Column Remarks:
     *   所属城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.city_id
     *
     * @mbg.generated
     */
    private Integer cityId;

    /**
     * Database Column Remarks:
     *   图片尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.pic_size
     *
     * @mbg.generated
     */
    private String picSize;

    /**
     * Database Column Remarks:
     *   广告位标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.position_desc
     *
     * @mbg.generated
     */
    private String positionDesc;

    /**
     * Database Column Remarks:
     *   广告标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.advert_title
     *
     * @mbg.generated
     */
    private String advertTitle;

    /**
     * Database Column Remarks:
     *   目标类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.target_type
     *
     * @mbg.generated
     */
    private Byte targetType;

    /**
     * Database Column Remarks:
     *   目标地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.target_val
     *
     * @mbg.generated
     */
    private String targetVal;

    /**
     * Database Column Remarks:
     *   广告类型,1:图文2:文字3:视频
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.advert_type
     *
     * @mbg.generated
     */
    private Byte advertType;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.image_path
     *
     * @mbg.generated
     */
    private String imagePath;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.start_time
     *
     * @mbg.generated
     */
    private Integer startTime;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.end_time
     *
     * @mbg.generated
     */
    private Integer endTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.utime
     *
     * @mbg.generated
     */
    private Integer utime;

    /**
     * Database Column Remarks:
     *   2:已上架 1:已下架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert_content.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_advert_content
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.id
     *
     * @return the value of tb_advert_content.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.id
     *
     * @param id the value for tb_advert_content.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.position_id
     *
     * @return the value of tb_advert_content.position_id
     *
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.position_id
     *
     * @param positionId the value for tb_advert_content.position_id
     *
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.city_id
     *
     * @return the value of tb_advert_content.city_id
     *
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.city_id
     *
     * @param cityId the value for tb_advert_content.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.pic_size
     *
     * @return the value of tb_advert_content.pic_size
     *
     * @mbg.generated
     */
    public String getPicSize() {
        return picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.pic_size
     *
     * @param picSize the value for tb_advert_content.pic_size
     *
     * @mbg.generated
     */
    public void setPicSize(String picSize) {
        this.picSize = picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.position_desc
     *
     * @return the value of tb_advert_content.position_desc
     *
     * @mbg.generated
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.position_desc
     *
     * @param positionDesc the value for tb_advert_content.position_desc
     *
     * @mbg.generated
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.advert_title
     *
     * @return the value of tb_advert_content.advert_title
     *
     * @mbg.generated
     */
    public String getAdvertTitle() {
        return advertTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.advert_title
     *
     * @param advertTitle the value for tb_advert_content.advert_title
     *
     * @mbg.generated
     */
    public void setAdvertTitle(String advertTitle) {
        this.advertTitle = advertTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.target_type
     *
     * @return the value of tb_advert_content.target_type
     *
     * @mbg.generated
     */
    public Byte getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.target_type
     *
     * @param targetType the value for tb_advert_content.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(Byte targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.target_val
     *
     * @return the value of tb_advert_content.target_val
     *
     * @mbg.generated
     */
    public String getTargetVal() {
        return targetVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.target_val
     *
     * @param targetVal the value for tb_advert_content.target_val
     *
     * @mbg.generated
     */
    public void setTargetVal(String targetVal) {
        this.targetVal = targetVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.advert_type
     *
     * @return the value of tb_advert_content.advert_type
     *
     * @mbg.generated
     */
    public Byte getAdvertType() {
        return advertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.advert_type
     *
     * @param advertType the value for tb_advert_content.advert_type
     *
     * @mbg.generated
     */
    public void setAdvertType(Byte advertType) {
        this.advertType = advertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.sort_order
     *
     * @return the value of tb_advert_content.sort_order
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.sort_order
     *
     * @param sortOrder the value for tb_advert_content.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.image_path
     *
     * @return the value of tb_advert_content.image_path
     *
     * @mbg.generated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.image_path
     *
     * @param imagePath the value for tb_advert_content.image_path
     *
     * @mbg.generated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.start_time
     *
     * @return the value of tb_advert_content.start_time
     *
     * @mbg.generated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.start_time
     *
     * @param startTime the value for tb_advert_content.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.end_time
     *
     * @return the value of tb_advert_content.end_time
     *
     * @mbg.generated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.end_time
     *
     * @param endTime the value for tb_advert_content.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.ctime
     *
     * @return the value of tb_advert_content.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.ctime
     *
     * @param ctime the value for tb_advert_content.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.utime
     *
     * @return the value of tb_advert_content.utime
     *
     * @mbg.generated
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.utime
     *
     * @param utime the value for tb_advert_content.utime
     *
     * @mbg.generated
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.status
     *
     * @return the value of tb_advert_content.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.status
     *
     * @param status the value for tb_advert_content.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.admin_id
     *
     * @return the value of tb_advert_content.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.admin_id
     *
     * @param adminId the value for tb_advert_content.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert_content.remarks
     *
     * @return the value of tb_advert_content.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert_content.remarks
     *
     * @param remarks the value for tb_advert_content.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}